export interface ToolDefinition {
  id: string
  name: string
  category: ToolCategory
  description: string
  path: string
  tags: string[]
}

export const categories = [
  { id: 'time', name: 'Time & Productivity' },
  { id: 'developer', name: 'Developer Tools' },
  { id: 'design', name: 'Design Tools' },
  { id: 'security', name: 'Security Tools' },
  { id: 'utility', name: 'Utility Tools' },
  { id: 'file', name: 'File Tools' },
  { id: 'system', name: 'System Tools' },
  { id: 'ai', name: 'AI Utilities' },
  { id: 'audio', name: 'Audio / Music' },
  { id: 'student', name: 'Student Tools' },
] as const

export type ToolCategory = (typeof categories)[number]['name']

const descriptions: Record<string, string> = {
  'Clock': '現在時刻と日付をすばやく確認します',
  'JSON Formatter': 'JSON を整形・検証します',
  'Base64 Encoder': 'テキストを Base64 エンコード／デコードします',
  'Password Generator': '強力なランダムパスワードを生成します',
}

const makeTool = (name: string, category: ToolCategory, tags: string[] = []): ToolDefinition => {
  const id = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

  return {
    id,
    name,
    category,
    description: descriptions[name] ?? `${name} をすばやく使えるモバイル対応ツール`,
    path: `/tools/${id}`,
    tags: [category.toLowerCase(), ...tags],
  }
}

export const tools: ToolDefinition[] = [
  makeTool('Clock', 'Time & Productivity', ['time', 'clock']),
  makeTool('Analog Clock', 'Time & Productivity', ['time', 'analog', 'clock']),
  makeTool('World Clock', 'Time & Productivity', ['time', 'world', 'clock']),
  makeTool('Stopwatch', 'Time & Productivity', ['time', 'stopwatch']),
  makeTool('Timer', 'Time & Productivity', ['time', 'timer']),
  makeTool('Pomodoro', 'Time & Productivity', ['time', 'pomodoro']),
  makeTool('Focus Timer', 'Time & Productivity', ['time', 'focus', 'timer']),
  makeTool('Meeting Timer', 'Time & Productivity', ['time', 'meeting', 'timer']),
  makeTool('Countdown', 'Time & Productivity', ['time', 'countdown']),
  makeTool('Alarm', 'Time & Productivity', ['time', 'alarm']),
  makeTool('Habit Tracker', 'Time & Productivity', ['time', 'habit', 'tracker']),
  makeTool('Daily Planner', 'Time & Productivity', ['time', 'daily', 'planner']),
  makeTool('Calendar', 'Time & Productivity', ['time', 'calendar']),
  makeTool('Timeline Maker', 'Time & Productivity', ['time', 'timeline', 'maker']),
  makeTool('Timezone Compare', 'Time & Productivity', ['time', 'timezone', 'compare']),
  makeTool('Study Session Tracker', 'Time & Productivity', ['time', 'study', 'session', 'tracker']),
  makeTool('JSON Formatter', 'Developer Tools', ['developer', 'json', 'formatter']),
  makeTool('YAML Formatter', 'Developer Tools', ['developer', 'yaml', 'formatter']),
  makeTool('XML Formatter', 'Developer Tools', ['developer', 'xml', 'formatter']),
  makeTool('HTML Formatter', 'Developer Tools', ['developer', 'html', 'formatter']),
  makeTool('CSS Formatter', 'Developer Tools', ['developer', 'css', 'formatter']),
  makeTool('JS Formatter', 'Developer Tools', ['developer', 'js', 'formatter']),
  makeTool('SQL Formatter', 'Developer Tools', ['developer', 'sql', 'formatter']),
  makeTool('Markdown Preview', 'Developer Tools', ['developer', 'markdown', 'preview']),
  makeTool('Base64 Encoder', 'Developer Tools', ['developer', 'base64', 'encoder']),
  makeTool('URL Encoder', 'Developer Tools', ['developer', 'url', 'encoder']),
  makeTool('URL Decoder', 'Developer Tools', ['developer', 'url', 'decoder']),
  makeTool('JWT Decoder', 'Developer Tools', ['developer', 'jwt', 'decoder']),
  makeTool('UUID Generator', 'Developer Tools', ['developer', 'uuid', 'generator']),
  makeTool('Hash Generator', 'Developer Tools', ['developer', 'hash', 'generator']),
  makeTool('SHA256 Generator', 'Developer Tools', ['developer', 'sha256', 'generator']),
  makeTool('MD5 Generator', 'Developer Tools', ['developer', 'md5', 'generator']),
  makeTool('HMAC Generator', 'Developer Tools', ['developer', 'hmac', 'generator']),
  makeTool('Regex Tester', 'Developer Tools', ['developer', 'regex', 'tester']),
  makeTool('Cron Builder', 'Developer Tools', ['developer', 'cron', 'builder']),
  makeTool('Diff Checker', 'Developer Tools', ['developer', 'diff', 'checker']),
  makeTool('HTTP Status Lookup', 'Developer Tools', ['developer', 'http', 'status', 'lookup']),
  makeTool('MIME Type Lookup', 'Developer Tools', ['developer', 'mime', 'type', 'lookup']),
  makeTool('Color Converter', 'Developer Tools', ['developer', 'color', 'converter']),
  makeTool('API Request Tester', 'Developer Tools', ['developer', 'api', 'request', 'tester']),
  makeTool('Query String Parser', 'Developer Tools', ['developer', 'query', 'string', 'parser']),
  makeTool('Timestamp Converter', 'Developer Tools', ['developer', 'timestamp', 'converter']),
  makeTool('Unix Time Converter', 'Developer Tools', ['developer', 'unix', 'time', 'converter']),
  makeTool('Code Minifier', 'Developer Tools', ['developer', 'code', 'minifier']),
  makeTool('Code Beautifier', 'Developer Tools', ['developer', 'code', 'beautifier']),
  makeTool('Lorem Ipsum Generator', 'Developer Tools', ['developer', 'lorem', 'ipsum', 'generator']),
  makeTool('ASCII Table', 'Developer Tools', ['developer', 'ascii', 'table']),
  makeTool('Unicode Inspector', 'Developer Tools', ['developer', 'unicode', 'inspector']),
  makeTool('Text Compare', 'Developer Tools', ['developer', 'text', 'compare']),
  makeTool('JSON Diff', 'Developer Tools', ['developer', 'json', 'diff']),
  makeTool('ENV Parser', 'Developer Tools', ['developer', 'env', 'parser']),
  makeTool('Color Picker', 'Design Tools', ['design', 'color', 'picker']),
  makeTool('Palette Generator', 'Design Tools', ['design', 'palette', 'generator']),
  makeTool('Gradient Generator', 'Design Tools', ['design', 'gradient', 'generator']),
  makeTool('Glassmorphism Generator', 'Design Tools', ['design', 'glassmorphism', 'generator']),
  makeTool('Shadow Generator', 'Design Tools', ['design', 'shadow', 'generator']),
  makeTool('Border Radius Generator', 'Design Tools', ['design', 'border', 'radius', 'generator']),
  makeTool('CSS Animation Generator', 'Design Tools', ['design', 'css', 'animation', 'generator']),
  makeTool('SVG Blob Generator', 'Design Tools', ['design', 'svg', 'blob', 'generator']),
  makeTool('SVG Wave Generator', 'Design Tools', ['design', 'svg', 'wave', 'generator']),
  makeTool('Favicon Generator', 'Design Tools', ['design', 'favicon', 'generator']),
  makeTool('Font Preview', 'Design Tools', ['design', 'font', 'preview']),
  makeTool('Contrast Checker', 'Design Tools', ['design', 'contrast', 'checker']),
  makeTool('Password Generator', 'Security Tools', ['security', 'password', 'generator']),
  makeTool('Password Strength Checker', 'Security Tools', ['security', 'password', 'strength', 'checker']),
  makeTool('Secure Notes', 'Security Tools', ['security', 'secure', 'notes']),
  makeTool('Random Token Generator', 'Security Tools', ['security', 'random', 'token', 'generator']),
  makeTool('2FA Code Viewer', 'Security Tools', ['security', '2fa', 'code', 'viewer']),
  makeTool('Entropy Calculator', 'Security Tools', ['security', 'entropy', 'calculator']),
  makeTool('QR Generator', 'Utility Tools', ['utility', 'qr', 'generator']),
  makeTool('QR Reader', 'Utility Tools', ['utility', 'qr', 'reader']),
  makeTool('Barcode Generator', 'Utility Tools', ['utility', 'barcode', 'generator']),
  makeTool('Unit Converter', 'Utility Tools', ['utility', 'unit', 'converter']),
  makeTool('Currency Converter', 'Utility Tools', ['utility', 'currency', 'converter']),
  makeTool('File Size Converter', 'Utility Tools', ['utility', 'file', 'size', 'converter']),
  makeTool('BMI Calculator', 'Utility Tools', ['utility', 'bmi', 'calculator']),
  makeTool('Age Calculator', 'Utility Tools', ['utility', 'age', 'calculator']),
  makeTool('Tip Calculator', 'Utility Tools', ['utility', 'tip', 'calculator']),
  makeTool('Percentage Calculator', 'Utility Tools', ['utility', 'percentage', 'calculator']),
  makeTool('Random Picker', 'Utility Tools', ['utility', 'random', 'picker']),
  makeTool('Coin Flip', 'Utility Tools', ['utility', 'coin', 'flip']),
  makeTool('Dice Roller', 'Utility Tools', ['utility', 'dice', 'roller']),
  makeTool('Decision Wheel', 'Utility Tools', ['utility', 'decision', 'wheel']),
  makeTool('Text Counter', 'Utility Tools', ['utility', 'text', 'counter']),
  makeTool('Case Converter', 'Utility Tools', ['utility', 'case', 'converter']),
  makeTool('Clipboard Manager', 'Utility Tools', ['utility', 'clipboard', 'manager']),
  makeTool('Speech To Text', 'Utility Tools', ['utility', 'speech', 'to', 'text']),
  makeTool('Text To Speech', 'Utility Tools', ['utility', 'text', 'to', 'speech']),
  makeTool('Image Compressor', 'File Tools', ['file', 'image', 'compressor']),
  makeTool('Image Converter', 'File Tools', ['file', 'image', 'converter']),
  makeTool('Image Resizer', 'File Tools', ['file', 'image', 'resizer']),
  makeTool('PDF Merger', 'File Tools', ['file', 'pdf', 'merger']),
  makeTool('PDF Splitter', 'File Tools', ['file', 'pdf', 'splitter']),
  makeTool('PDF Compressor', 'File Tools', ['file', 'pdf', 'compressor']),
  makeTool('Audio Converter', 'File Tools', ['file', 'audio', 'converter']),
  makeTool('Video Converter', 'File Tools', ['file', 'video', 'converter']),
  makeTool('ZIP Extractor', 'File Tools', ['file', 'zip', 'extractor']),
  makeTool('File Checksum', 'File Tools', ['file', 'file', 'checksum']),
  makeTool('Device Info', 'System Tools', ['system', 'device', 'info']),
  makeTool('Browser Info', 'System Tools', ['system', 'browser', 'info']),
  makeTool('Screen Info', 'System Tools', ['system', 'screen', 'info']),
  makeTool('Battery Status', 'System Tools', ['system', 'battery', 'status']),
  makeTool('Network Info', 'System Tools', ['system', 'network', 'info']),
  makeTool('FPS Monitor', 'System Tools', ['system', 'fps', 'monitor']),
  makeTool('Storage Inspector', 'System Tools', ['system', 'storage', 'inspector']),
  makeTool('User Agent Viewer', 'System Tools', ['system', 'user', 'agent', 'viewer']),
  makeTool('WebRTC Tester', 'System Tools', ['system', 'webrtc', 'tester']),
  makeTool('Prompt Formatter', 'AI Utilities', ['ai', 'prompt', 'formatter']),
  makeTool('Prompt Generator', 'AI Utilities', ['ai', 'prompt', 'generator']),
  makeTool('Token Counter', 'AI Utilities', ['ai', 'token', 'counter']),
  makeTool('AI Chat Export Cleaner', 'AI Utilities', ['ai', 'ai', 'chat', 'export']),
  makeTool('Markdown AI Formatter', 'AI Utilities', ['ai', 'markdown', 'ai', 'formatter']),
  makeTool('Transcript Cleaner', 'AI Utilities', ['ai', 'transcript', 'cleaner']),
  makeTool('BPM Tapper', 'Audio / Music', ['audio', 'bpm', 'tapper']),
  makeTool('Metronome', 'Audio / Music', ['audio', 'metronome']),
  makeTool('MIDI Viewer', 'Audio / Music', ['audio', 'midi', 'viewer']),
  makeTool('Chord Finder', 'Audio / Music', ['audio', 'chord', 'finder']),
  makeTool('Scale Finder', 'Audio / Music', ['audio', 'scale', 'finder']),
  makeTool('Frequency Generator', 'Audio / Music', ['audio', 'frequency', 'generator']),
  makeTool('Audio Visualizer', 'Audio / Music', ['audio', 'audio', 'visualizer']),
  makeTool('Formula Sheet', 'Student Tools', ['student', 'formula', 'sheet']),
  makeTool('Equation Solver', 'Student Tools', ['student', 'equation', 'solver']),
  makeTool('Graph Plotter', 'Student Tools', ['student', 'graph', 'plotter']),
  makeTool('GPA Calculator', 'Student Tools', ['student', 'gpa', 'calculator']),
  makeTool('Flashcards', 'Student Tools', ['student', 'flashcards']),
  makeTool('Study Randomizer', 'Student Tools', ['student', 'study', 'randomizer']),
]

export const toolsById = new Map(tools.map((tool) => [tool.id, tool]))

export const groupedTools = categories.map((category) => ({
  ...category,
  tools: tools.filter((tool) => tool.category === category.name),
}))
